<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F5ANUFB" failures="1" tests="2" name="Test" time="26.259" errors="0" timestamp="2023-05-30T15:52:08 IST">
  <testcase classname="Scenario_Component.Scenario_Login" name="invalidLogin" time="4.284"/>
  <testcase classname="Scenario_Component.Scenario_Login" name="invalidLogin" time="2.166">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Failed. Actual Result is: Sorry we were unable to complete this step because :">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Failed. Actual Result is: Sorry we were unable to complete this step because :
at Scenario_Component.Scenario_Login.invalidLogin(Scenario_Login.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Test -->
